source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Education Platform' do
  
  pod 'Localize-Swift'
  pod 'TPKeyboardAvoiding'
  pod 'MBProgressHUD', :git => "https://github.com/jdg/MBProgressHUD.git"
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'PureLayout'
  pod 'FontAwesomeKit'
  pod 'PasswordTextField'
  pod 'NVActivityIndicatorView'
  pod 'RealmSwift'
  pod 'EAIntroView'
  pod 'IQKeyboardManager'
  pod 'Alamofire'
  pod 'JSONModel'
  pod 'EVReflection'
  pod 'CNPPopupController'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'MSRangeSlider'
  pod 'Google/SignIn'
  pod 'Parse'
  pod 'JSQMessagesViewController'
  pod 'TTRangeSlider'
  pod 'HCSStarRatingView'
  pod 'iCarousel'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'AKPickerView'
  pod 'KSTokenView'
  pod 'STPopup'
  pod 'CRNetworkButton'
  pod 'Starscream'
  pod 'TTTAttributedLabel'
  pod 'ESPullToRefresh'
  pod 'MXSegmentedPager'
  pod 'ExpandableTableViewController'
  pod 'INSPhotoGallery'
  pod 'DZNEmptyDataSet'
  pod 'NYTPhotoViewer'
end

